/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupStageRouteImport } from './routes/groupStage'
import { Route as FecesCupRouteImport } from './routes/fecesCup'
import { Route as EditRouteImport } from './routes/edit'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupStageRoute = GroupStageRouteImport.update({
  id: '/groupStage',
  path: '/groupStage',
  getParentRoute: () => rootRouteImport,
} as any)
const FecesCupRoute = FecesCupRouteImport.update({
  id: '/fecesCup',
  path: '/fecesCup',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/fecesCup': typeof FecesCupRoute
  '/groupStage': typeof GroupStageRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/fecesCup': typeof FecesCupRoute
  '/groupStage': typeof GroupStageRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit': typeof EditRoute
  '/fecesCup': typeof FecesCupRoute
  '/groupStage': typeof GroupStageRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/edit' | '/fecesCup' | '/groupStage' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/edit' | '/fecesCup' | '/groupStage' | '/login'
  id: '__root__' | '/' | '/edit' | '/fecesCup' | '/groupStage' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  FecesCupRoute: typeof FecesCupRoute
  GroupStageRoute: typeof GroupStageRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groupStage': {
      id: '/groupStage'
      path: '/groupStage'
      fullPath: '/groupStage'
      preLoaderRoute: typeof GroupStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fecesCup': {
      id: '/fecesCup'
      path: '/fecesCup'
      fullPath: '/fecesCup'
      preLoaderRoute: typeof FecesCupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  FecesCupRoute: FecesCupRoute,
  GroupStageRoute: GroupStageRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
